vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        ticket_image:
            uri_prefix: /ticket_image
            upload_destination: '%kernel.project_dir%/public/ticket_image'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true


